
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Wed Jun 26 10:20:24 GMT 2002
//----------------------------------------------------

package slime.sfcparser;

/** CUP generated class containing symbol constants. */
public class SFCSymbols {
  /* terminals */
  public static final int LPSET = 12;
  public static final int OUTPUT = 37;
  public static final int COMMENT = 31;
  public static final int INPUT = 36;
  public static final int INTEGER = 41;
  public static final int LPAREN = 10;
  public static final int REPEAT = 38;
  public static final int RPAREN = 11;
  public static final int NOT = 9;
  public static final int SEMICOLON = 21;
  public static final int AND = 7;
  public static final int LT = 14;
  public static final int OR = 8;
  public static final int COMMA = 20;
  public static final int RPSET = 13;
  public static final int DIV = 5;
  public static final int UNTIL = 39;
  public static final int GEQ = 17;
  public static final int SFCPRG = 32;
  public static final int ASSIGN = 26;
  public static final int IF = 33;
  public static final int PROCESS = 30;
  public static final int EOF = 0;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int ADD = 2;
  public static final int JOIN = 29;
  public static final int MOD = 6;
  public static final int NEQ = 19;
  public static final int SPLIT = 28;
  public static final int EQ = 18;
  public static final int BOOLTYPE = 25;
  public static final int ELSE = 34;
  public static final int SKIP = 27;
  public static final int WHILE = 35;
  public static final int INTTYPE = 24;
  public static final int LEQ = 16;
  public static final int FALSE = 23;
  public static final int GT = 15;
  public static final int SUB = 3;
  public static final int IDENTIFIER = 40;

  /* non terminals */
  static final int vardeclaration = 13;
  static final int procidlist = 25;
  static final int expr = 5;
  static final int stmtatomic = 3;
  static final int stmtloopwhile = 18;
  static final int vartype = 7;
  static final int NT$0 = 26;
  static final int stmtblock = 11;
  static final int $START = 0;
  static final int op = 9;
  static final int sfcprogram = 4;
  static final int stmtinput = 14;
  static final int stmtjoin = 21;
  static final int constval = 8;
  static final int process = 23;
  static final int stmtsplit = 20;
  static final int stmtif = 16;
  static final int stmtoutput = 15;
  static final int assignment = 12;
  static final int stmtlist = 10;
  static final int processlist = 24;
  static final int sfcbegin = 1;
  static final int stmtifelse = 17;
  static final int var = 6;
  static final int stmtlooprepeat = 19;
  static final int stmtdummy = 22;
  static final int stmt = 2;
}

