
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 27 21:39:11 GMT 2002
//----------------------------------------------------

package slime.sfcparser;

/** CUP generated class containing symbol constants. */
public class SFCSymbols {
  /* terminals */
  public static final int LPSET = 14;
  public static final int OUTPUT = 39;
  public static final int COMMENT = 33;
  public static final int INPUT = 38;
  public static final int INTEGER = 4;
  public static final int LPAREN = 12;
  public static final int REPEAT = 40;
  public static final int RPAREN = 13;
  public static final int NOT = 11;
  public static final int SEMICOLON = 23;
  public static final int AND = 9;
  public static final int LT = 16;
  public static final int OR = 10;
  public static final int COMMA = 22;
  public static final int RPSET = 15;
  public static final int DIV = 8;
  public static final int UNTIL = 41;
  public static final int GEQ = 19;
  public static final int SFCPRG = 34;
  public static final int IF = 35;
  public static final int ASSIGN = 28;
  public static final int DOT = 2;
  public static final int PROCESS = 32;
  public static final int EOF = 0;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int MUL = 7;
  public static final int ADD = 5;
  public static final int JOIN = 31;
  public static final int NEQ = 21;
  public static final int SPLIT = 30;
  public static final int EQ = 20;
  public static final int BOOLTYPE = 27;
  public static final int ELSE = 36;
  public static final int SKIP = 29;
  public static final int WHILE = 37;
  public static final int INTTYPE = 26;
  public static final int LEQ = 18;
  public static final int FALSE = 25;
  public static final int GT = 17;
  public static final int SUB = 6;
  public static final int IDENTIFIER = 3;

  /* non terminals */
  static final int vardeclaration = 13;
  static final int procidlist = 25;
  static final int expr = 5;
  static final int stmtatomic = 3;
  static final int stmtloopwhile = 18;
  static final int vartype = 7;
  static final int NT$0 = 26;
  static final int stmtblock = 11;
  static final int $START = 0;
  static final int op = 9;
  static final int sfcprogram = 4;
  static final int stmtinput = 14;
  static final int stmtjoin = 21;
  static final int constval = 8;
  static final int process = 23;
  static final int stmtsplit = 20;
  static final int stmtif = 16;
  static final int stmtoutput = 15;
  static final int assignment = 12;
  static final int stmtlist = 10;
  static final int processlist = 24;
  static final int sfcbegin = 1;
  static final int stmtifelse = 17;
  static final int var = 6;
  static final int stmtlooprepeat = 19;
  static final int stmtdummy = 22;
  static final int stmt = 2;
}

