/* Generated by Together */

package slime.gui;

import slime.gui.listener.MenuHoerer;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JMenuBar;
import java.awt.event.*;
import javax.swing.*;
import slime.editor.Editor;

public class GuiMenu extends JMenuBar  {
    JFrame jframe;
    MenuHoerer me;
    String[] fileItems;
    String[] optionItems;
    JMenu filemenu;
    JMenu optionmenu;
    char[] fileShortcuts =  { 'N','O','S','E'};
    char[] optionShortcuts =  { 'C','L','H','C'};
   /**
    *  Default Konstruktor des Menues
    */

   public GuiMenu(MenuHoerer mem){
      this.me = mem;
      fileItems   = new String []
                        {"New", "Open","Save","Exit"};
      optionItems = new String []
                         {"Check","Layout","Help","Close"};
      filemenu = new JMenu("File");
      optionmenu = new JMenu("Options");

      //Assemble the Filemenues with he mnemonics
      for(int i=0; i<fileItems.length;i++){
          JMenuItem item = new JMenuItem(fileItems[i]);
          item.addActionListener(me);
          filemenu.add(item);
      }
      //Assemble the optionmenues with the mnemonics
      for(int i=0; i<optionItems.length;i++){
          JMenuItem item = new JMenuItem(optionItems[i],optionShortcuts[i]);
          item.addActionListener(me);
          optionmenu.add(item);
      }
       add(filemenu);
       add(optionmenu);
    }
}



