/* Generated by Together */

package slime.gui;

 import java.awt.*;
 import slime.gui.listener.*;
 import javax.swing.*;
 import slime.editor.Editor;
 import slime.absynt.SFC;

/**
 * Die Klasse erzeugt die Oberflaechen fuer die Slime Anwendung
 * @author Norbert Boeck fuer swprakt02
 */
   public class GuiStart extends JMenuBar {
       //Membervariable
      private JFrame jFrame;
      private JButton jButton;
      private Editor editor;
      private JMenuItem item;
      private JPanel jPanel;
      private JLabel jLabel;
      private String sfcName = "dummysfc";
      private JTextField sfcfield;
      private SFC sfc ;
   /**
    * @link aggregationByValue
    * @clientCardinality 1
    * @supplierCardinality 1
    */
    private GuiMenu lnkGuiMenu;
    JFrame jFenster;
    MenuHoerer mes;
   /**
    * Der default Konstruktor der Klasse GuiStart
    */
   public GuiStart(JFrame jfenetre) {
     this.jFenster = jfenetre;
     jLabel = new JLabel();
   }
    /**
     * Verknuepft den Button mit dem Listener Ereignishoerer
     * @param hoerer wird explizit uebergeben
     *
     */
   public void verdrahtenguiMenu(MenuHoerer mem){
       this.mes = mem;
       lnkGuiMenu = new GuiMenu(mes);
       jFenster.getContentPane().add("Center",jLabel);
       jFenster.getContentPane().add("North",lnkGuiMenu);
       jFenster.pack();
       jFenster.addWindowListener(new BasicWindowMonitor());
       jFenster.setSize(300,400);
       jFenster.show(true);
       jFenster.setVisible(true);
    }
   /**
    * creates an instance of editor
    *
    */
   public void createEditor(){
       editor = new Editor();
       JPanel jpanel = new JPanel();
       jpanel.setLayout(new FlowLayout(FlowLayout.LEADING));

       JPanel pospanel = new JPanel();
       pospanel.setLayout(new GridLayout(1,1));
       pospanel.add(editor);

       jpanel.add(pospanel);
       jFrame = new JFrame();
       jFrame.setContentPane(pospanel);
       jFrame.setSize(1800,1800);
       jFrame.show(true);
       jFrame.setVisible(true);
    }
   public void exit(){
         System.exit(0);
     }


}







