/* Generated by Together */

package slime.gui;

import slime.gui.listener.MenuHoerer;
import slime.gui.listener.Ereignishoerer;
import javax.swing.*;
import slime.gui.GuiDialog;
/**
 * Main class of the Slime project
 * makes an instantance of JFrame, put
 * it as an parameter into the instance
 * of GuiStart and put into the list
 * of Menuehoerer
 *
 */
public class SlimeStart {
    public static void main(String[] args){
        JFrame jframe = new JFrame("SFC Project");
        GuiStart guiStart = new GuiStart(jframe);
        GuiDialog gu = new GuiDialog();
        MenuHoerer me = new MenuHoerer(guiStart,gu);
        guiStart.verdrahtenguiMenu(me);
    }
}
