

** Abstract
The repository collects the /sources/ of the ``Slime'' project (Sequential
Function Charts Modelling Environment), in the software programming lab
course ``Programming in the Many'', summer semester 2002, at the University
Kiel.

For the webpages of the course, see [[http://heim.ifi.uio.no/msteffen/teaching/softtech/ss02/pitm-slime/slime/][here]].


** Structure
This is the root of the Slime-project from the summer term 2002.  The
package contains the following files and subdirectories:

  

    - [[,/Readme.org]]:            this file
    - [[./Snapshots]]:         short description about major
                         development steps
    - sfcintro/          slides for an intro about sfc's
    - [[./requirements/]]      description of the task
    - review/            end-of-semester review, summary (including talk)
    - web/               web-site material for coordination,
                         tracking the progress etc.
    - org/               internal information about members etc

    - [[./cd]]/                info's for the cd-rom
    - [[./src/]]               the Java-sources
    - tex/               common LaTeX-macros 
    - lib/               external libraries (here the lex/yacc archives,
	                 included for better coordination.


** Historical notes

The repository has been migrated from ~cvs~ via svn (using ~cvs2svn~) and
from there to ~git~. Caveats concerning missing branches apply. Also the
/Snapshots/ (original svn revision tags) seem not to be preserved as git
labels in the final repository (see the [[./Snapshots]]-file).  Also, original
authors have not been preserved, as the original development was done all
via a common login ~swprakt~; in general, the contributors were the
different students in the course plus the course teacher.

#+BEGIN_QUOTE

############################################################
## $Id: Readme,v 1.12 2003-01-23 16:17:56 swprakt Exp $
############################################################

#+END_QUOTE

