/* Generated by Together */

package slime.gui.model;

 import slime.absynt.SFC;
 import java.io.*;

  public class FachKlasse implements Serializable {
       private String filename;
       protected SFC sfc;

      public FachKlasse(){
      }
      public void setFilename(String name){
               this.filename = name;
      }
      public String getFilename(){
               return this.filename;
      }
      public void setSFC(SFC sfc){
             this.sfc = sfc;
      }

     public FachKlasse(String t){
        this.filename = t;
     }
 }
