/* Generated by Together */

package slime.gui.model;
import slime.absynt.SFC;
import java.io.*;

public class NewSFC {
    SFC sfc;
    public NewSFC(){
    }
    public SFC getSFC(){
        sfc = new SFC();
        return sfc;
    }
}
