/* Generated by Together */

package slime.gui.model;
   import slime.absynt.SFC;
   import java.io.*;
   import slime.editor.*;

public class OpenSFC extends FachKlasse {

   ObjectInputStream in;
   /**
    *  OpenSFC used setFilename of the derived class Fachklasse
    *  to store the dateinmame
    *  @param dateiname
    */
   public OpenSFC(String dateiname){
        this.setFilename(dateiname);
   }
  /*/ public void loadSFC(){
       // OpenSFC open = new OpenSFC(this.getFilename());
        sfc =  open.getSFC();
        Editor editor = new Editor(sfc);
      }*/
   public SFC loadSFC(){
       try{
           in = new ObjectInputStream(
           //new FileInputStream(this.getFilename()));
           new FileInputStream("eins.sfc"));
           sfc = (SFC)in.readObject();
       }catch(IOException e){
          System.out.println("Es gibt eine IOException");
       }
       catch(ClassNotFoundException u){
           System.out.println("Eine ClassNotFoundException ");
       }
        return sfc;
   }
}
