/* Generated by Together */

package slime.gui.model;

  import slime.absynt.SFC;
  import java.io.*;

   public class SaveSFC extends FachKlasse  {
      ObjectOutputStream out;
      public SaveSFC(String dateiname,SFC sfc){
         this.setFilename(dateiname);
         this.setSFC(sfc);
         Object o = (Object)sfc;
         try{
            out = new ObjectOutputStream(
               new FileOutputStream(this.getFilename()));
               out.writeObject(o);
        }catch(IOException e){
               System.out.println("Es gibt eine IOExcetion");
        }
     }
}

