##########################
# $Id: Makefile,v 1.1 2002-06-27 15:10:17 swprakt Exp $                       
# Makefile for slime.absynt.absfc 
# initially provided by Marco Wendel <mwe@informatik.uni-kiel.de> 
##########################
# $Log: not supported by cvs2svn $
#
##########################

############# Declaration of Path & Files ###########

PACKAGE=slime.absynt.absfc
ICLASSPATH=../../..

############# Compile Package SFCParser #############

all:
	javac -classpath $(ICLASSPATH) *.java

clean:
	rm -f *.class *.bak *~ *.tmp

