##########################
# $Id: Makefile,v 1.2 2002-06-28 08:03:09 swprakt Exp $                       
# Makefile for slime.absynt.absfc 
# initially provided by Marco Wendel <mwe@informatik.uni-kiel.de> 
##########################
# $Log: not supported by cvs2svn $
# Revision 1.1  2002/06/27 15:10:17  swprakt
# we should be using relative classpaths to our
# classpath root. the root is /home/swprakt/cvsroot/Slime/src
# (mwe)
#
#
##########################

############# Declaration of Path & Files ###########

PACKAGE=slime.absynt.absfc
# ICLASSPATH=../../..

############# Compile Package SFCParser #############

all:
	javac *.java

clean:
	rm -f *.class *.bak *~ *.tmp

