/* Generated by Together */

package slime.gui.listener;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Window;

public class BasicWindowMonitor extends WindowAdapter {
    public void windowClosing(WindowEvent e){
        Window window = e.getWindow();
        window.setVisible(false);
        window.dispose();
        System.exit(0);
    }
 }
