/* Generated by Together */

package slime.gui.listener;

import slime.gui.GuiDialog;
import slime.gui.GuiStart;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.*;
import slime.editor.*;

public class MenuHoerer implements ActionListener {
    GuiDialog dialog;
    GuiStart gui;
    JFrame jframe;
    /**
     * Kontruktor von Menuehoerer
     * uebergibt eine Instanz von JFrame
     * @param jfenster
     */
     public MenuHoerer(GuiStart gu,GuiDialog dia){
        this.gui = gu;
        this.dialog = dia;
     }
     private String t = "New";
     private String name ="dummy";
     public MenuHoerer(){
     }
    //loest eine Aktion nachdem der Anwender das gewuenschte Item gedrueckt hat
    public void actionPerformed(ActionEvent e){
          t = e.getActionCommand();
          if(t.equals("New")){
             gui.createEditor();
          }
         if(t.equals("Open")){
             dialog.openSFC();
         }
         if(t.equals("Save")){
            dialog.saveSFC();

         }
        if(t.equals("Exit")){
            gui.exit();
         }
    }
}



